import type { Sentence } from './types';

export const mockSentences: Sentence[] = [
  {
    id: 1,
    german: "Wie geht es dir?",
    english: "How are you?",
    audio: "how-are-you.mp3",
    source_word_de: "gehen",
    is_learning: false,
    stability: 0,
    difficulty: 0,
    elapsed_days: 0,
    scheduled_days: 0,
    last_review: new Date().toISOString(),
    state: 0,
  },
  {
    id: 2,
    german: "Ich verstehe nur Bahnhof.",
    english: "It's all Greek to me.",
    audio: "greek-to-me.mp3",
    source_word_de: "Bahnhof",
    is_learning: false,
    stability: 0,
    difficulty: 0,
    elapsed_days: 0,
    scheduled_days: 0,
    last_review: new Date().toISOString(),
    state: 0,
  },
  {
    id: 3,
    german: "Das ist mir Wurst.",
    english: "I don't care.",
    audio: "dont-care.mp3",
    source_word_de: "Wurst",
    is_learning: true,
    stability: 2.5,
    difficulty: 3.0,
    elapsed_days: 1,
    scheduled_days: 3,
    last_review: new Date().toISOString(),
    state: 1,
  },
  {
    id: 4,
    german: "Aller Anfang ist schwer.",
    english: "All beginnings are hard.",
    audio: "beginnings.mp3",
    source_word_de: "Anfang",
    is_learning: false,
    stability: 0,
    difficulty: 0,
    elapsed_days: 0,
    scheduled_days: 0,
    last_review: new Date().toISOString(),
    state: 0,
  },
  {
    id: 5,
    german: "Übung macht den Meister.",
    english: "Practice makes perfect.",
    audio: "practice.mp3",
    source_word_de: "Übung",
    is_learning: true,
    stability: 10.2,
    difficulty: 2.1,
    elapsed_days: 5,
    scheduled_days: 14,
    last_review: new Date().toISOString(),
    state: 2,
  },
  {
    id: 6,
    german: "Ende gut, alles gut.",
    english: "All's well that ends well.",
    audio: "ends-well.mp3",
    source_word_de: "Ende",
    is_learning: false,
    stability: 0,
    difficulty: 0,
    elapsed_days: 0,
    scheduled_days: 0,
    last_review: new Date().toISOString(),
    state: 0,
  },
  {
    id: 7,
    german: "Ich habe Hunger.",
    english: "I am hungry.",
    audio: "hungry.mp3",
    source_word_de: "Hunger",
    is_learning: false,
    stability: 0,
    difficulty: 0,
    elapsed_days: 0,
    scheduled_days: 0,
    last_review: new Date().toISOString(),
    state: 0,
  }
];
